### PR TITLE
Indicator hotfix

### LINKED ISSUE #272: 🐛 NavigationPane sticky state not preserved
**Describe the bug**

fluent_pane_bug

**To Reproduce**

You can see that on example app. Go the the settings pane and change theme (light, dark) and the sticky move from the previous selected pane to settings.

**Expected behavior**

The sticky must not be animate when we are already on the good pane.

Edit: 3.10.0 regression

### PR DESCRIPTION
**Pull request by bdlukaa**
Fixes #272

## Pre-launch Checklist

- [x] I have updated `CHANGELOG.md` with my changes  
- [ ] I have run "optimize/organize imports" on all changed files
- [x] I have added/updated relevant documentation

### CODE REVIEW

File: lib/src/controls/navigation/navigation_view/view.dart [hunk 1]
```diff
@@ -129,6 +133,27 @@ class NavigationViewState extends State<NavigationView> {
...
       oldIndex = oldWidget.pane?.selected ?? 0;
     }
+
+    if (oldWidget.pane?.effectiveItems.length !=
+        widget.pane?.effectiveItems.length) {
+      if (widget.pane?.effectiveItems.length != null) {
+        generateKeys();
+      }
+    }
+  }
```
Comment (bdlukaa) [inline lib/src/controls/navigation/navigation_view/view.dart:143]: Generate new keys when the items are added or removed
