### PR TITLE
fix: Update NumberBox formatting pattern for precision

### LINKED ISSUE #1079: 🐛 Numberbox format notwork when precision bigger then 4
**Describe the bug**
Use NumberBox to input 0.0001 and set precision, it will format display to 0

**To Reproduce**

```
NumberBox(
  precision:4,
  value:0.0001,
  onChanged:(){},
)
```

### PR DESCRIPTION
**Pull request by FourLeafTec**
fix #1079 .
By add NumberFormat pattern [L632](https://github.com/FourLeafTec/fluent_ui/blob/47fba0fde8a02e9d49546af48800c2926bdd24a5/lib/src/controls/form/number_box.dart#L632).

### CODE REVIEW

**Comment by bdlukaa** [comment]
Great! Would you mind adding this to the CHANGELOG?

**Comment by FourLeafTec** [comment]
Sure, but I just realized that this PR is a bit too simple, and I would like to add some more content:

1. Create properties to store the pattern instead of concatenating them each time
2. Allow users to pass in patterns to customize the format
3. Allow a format method to customize the formatting, but this will affect the parser, and I haven't figured this out yet. I would like to hear your thoughts.

It seems that the PR has also failed to merge, so I will find some time later to complete this part and then modify the CHANGLOG.. Is that okay?

**Comment by bdlukaa** [comment]
Sounds okay to me!

**Comment by bdlukaa** [comment]
@FourLeafTec let me known when this is ready for review!

File: lib/src/controls/form/number_box.dart [hunk 1]
```diff
@@ -10,6 +9,12 @@ import 'package:math_expressions/math_expressions.dart';
 const kNumberBoxOverlayWidth = 60.0;
 const kNumberBoxOverlayHeight = 100.0;
 
+typedef FormatFunction = String? Function(num? number);
+
+abstract interface class Formatter {
+  String format(dynamic number);
+}
+
```
Comment (bdlukaa) [inline lib/src/controls/form/number_box.dart:17]: These could be named `NumberBoxFormatCallback` and `NumberBoxFormatter`, respectivelly, to avoid confusion with other formatters

File: lib/src/controls/form/number_box.dart [hunk 2]
```diff
@@ -95,8 +100,23 @@ class NumberBox<T extends num> extends StatefulWidget {
...
+  // The formatter for the number box. The formatter is used to format the
+  // number when the user input a value. If formatter set,precision, pattern and format
+  // must be null.
+  final Formatter? formatter;
+
+  /// The format function for the number box. The format function is used to
+  /// format the number when the user input a value. If format set,precision,
+  /// pattern and formatter must be null.
+  final FormatFunction? format;
```
Comment (bdlukaa) [inline lib/src/controls/form/number_box.dart:119]:
```suggestion
  /// value. 
  ///
  /// If set, [pattern], [formatter] and [format] must be `null`. 
  ///
  /// Default is 2.
  final int? precision;

  /// The parttern for the number box. The pattern is used to format the number
  /// when the user inputs a value.
  ///
  /// If set, [precision], [formatter] and [format] must be `null`. 
  final String? pattern;

  /// The formatter for the number box. The formatter is used to format the
  /// number when the user inputs a value.
  ///
  /// If set, [pattern], [precision] and [format] must be `null`. 
  final Formatter? formatter;

  /// The format function for the number box. The format function is used to
  /// format the number when the user input a value.
  ///
  /// If set, [pattern], [formatter] and [precision] must be `null`. 
  final FormatFunction? format;
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,8 @@
+## next
+
+- fix: `NumberBox` format not work when precision bigger then 4.
+- feat: Add `NumberBox.pattern`, `NumberBox.formatter`, `NumberBox.format` to Numberbox.
```
Comment (bdlukaa) [inline CHANGELOG.md:4]:
```suggestion
- feat: ¹ `NumberBox` now supports precision greater than 4. ² Add `NumberBox.pattern`, `NumberBox.formatter`, `NumberBox.format` ([#1080](https://github.com/bdlukaa/fluent_ui/pull/1080))
```

**Review by bdlukaa — CHANGES_REQUESTED** [review]

File: lib/src/controls/form/number_box.dart (hunk 1 above)
Comment (FourLeafTec) [reply lib/src/controls/form/number_box.dart:17]: The `Formatter` should be named `NumberBoxFormatter`.

But the `FormatFunction` should be named `NumberBoxFormatFunction`.
This method is not a formatted callback, but rather it is used to format numbers.

My changes to the precision formatting function can be divided into three parts:

1. Simple specification of precision length: This allows users to directly specify the desired precision of a number without using any formatting methods.

2. Incorporating an inline formatting method: This method remains the same as before and is still the most commonly used way to format numbers.

3. A more complex and general Formatter class: This class provides more flexibility in formatting numbers, including the ability to customize the formatting rules and use different formatting styles.

Users can choose from any of these three approaches to achieve the desired formatting.

Comment (bdlukaa) [reply lib/src/controls/form/number_box.dart:17]: Sure!

**Comment by FourLeafTec** [comment]
@bdlukaa Review please.

**Review by bdlukaa — APPROVED** [review]
